
name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
<<<<<<< HEAD
=======
  - voila
  - geopandas
>>>>>>> e0e8bba80f5322f05e387e2db0583c4229210929
  - rasterio=1.2.10
  - pip
  - pip:
    - folium==0.12.1
    - matplotlib==3.4.3
